[build]
  command = "npm run build && mkdir -p dist/tienda-cafe/browser/browser && cp -r dist/tienda-cafe/browser/* dist/tienda-cafe/browser/browser/"
  publish = "dist/tienda-cafe/browser/browser"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 