[build]
  command = "npm run build"
  publish = "dist/tienda-cafe/browser"

[build.environment]
  NODE_VERSION = "18"

# Disable the @netlify/angular-runtime plugin
[[plugins]]
  package = "@netlify/angular-runtime"
  [plugins.inputs]
    enabled = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 